apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  source:
    path: /prometheus
    repoURL: ////////////////
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true